echo "bad1.mesh" >> output.log
./meshalyzer bad1.mesh >> output.log
echo "bad_mesh.mesh" >> output.log
./meshalyzer bad_mesh.mesh >> output.log
echo "bad_mesh_too.mesh" >> output.log
./meshalyzer bad_mesh_too.mesh >> output.log
echo "example0.mesh" >> output.log
./meshalyzer example0.mesh >> output.log
echo "example1.mesh" >> output.log
./meshalyzer example1.mesh >> output.log
echo "example2.mesh" >> output.log
./meshalyzer example2.mesh >> output.log
echo "example3.mesh" >> output.log
./meshalyzer example3.mesh >> output.log
